format_version: 4
common:
  deploy_job: &deploy_job
    resources:
      - docker
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs

pipelines:
  'prm-deductions-gp-to-repo':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
    stages:
      - build:
          clean_workspace: true
          jobs:
            dependency_check:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dep
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test
            npm_install:
              resources:
                - docker
              artifacts:
                - build:
                    source: build
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build
      - docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: npm_install
                    source: build
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker
      # - test_docker:
      #     clean_workspace: true
      #     jobs:
      #       test:
      #         resources:
      #           - docker
      #         tasks:
      #           - exec:
      #               command: /bin/bash
      #               arguments:
      #                 - -c
      #                 - ./tasks test_docker
  # "prm-deductions-gp-to-repo.dev":
  #   group: deductions
  #   label_template: '${git[:8]}'
  #   materials:
  #     git:
  #       type: configrepo
  #     app:
  #       pipeline: prm-deductions-gp-to-repo
  #       stage: test_docker
  #     base_infra:
  #       pipeline: prm-deductions-infra
  #       stage: deploy_dev
  #   environment_variables:
  #     NHS_ENVIRONMENT: dev
  #   stages:
  #     - deploy:
  #         clean_workspace: true
  #         jobs:
  #           deploy: *deploy_job

  #     - test:
  #         clean_workspace: true
  #         jobs:
  #           smoke:
  #             resources:
  #               - docker
  #             tasks:
  #               - exec:
  #                   command: /bin/bash
  #                   arguments:
  #                     - -c
  #                     - ./tasks smoke_test
